# Generated by Django 3.0 on 2021-03-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JournalApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='branch_name',
            field=models.CharField(max_length=150, verbose_name='Название отделения'),
        ),
    ]
